# Generated by Django 2.0 on 2021-01-19 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='mimage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='mtype',
            new_name='Parti_type',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='user',
            new_name='Parti_user',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='mphone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='mimage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='mphone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='user',
            new_name='Res_user',
        ),
        migrations.RenameField(
            model_name='researcher',
            old_name='mspecial',
            new_name='Specialization',
        ),
        migrations.RenameField(
            model_name='reviewer',
            old_name='mimage',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='reviewer',
            old_name='mphone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='reviewer',
            old_name='user',
            new_name='Reviwer_user',
        ),
        migrations.RenameField(
            model_name='reviewer',
            old_name='mspecial',
            new_name='Specialization',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mactive',
            new_name='Active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='memail',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mcpassword',
            new_name='Firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mfname',
            new_name='Lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mlname',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='musertype',
            new_name='Role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mpassword',
        ),
    ]
