# Generated by Django 2.0 on 2021-01-19 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0002_auto_20210119_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Active',
        ),
    ]
