# Generated by Django 2.0 on 2021-01-23 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0003_remove_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='Parti_type',
        ),
    ]
