# Generated by Django 2.0 on 2021-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0004_remove_participant_parti_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher',
            name='Specialization',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='Specialization',
        ),
        migrations.AddField(
            model_name='participant',
            name='About',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='participant',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='researcher',
            name='About',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='researcher',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='About',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reviewer',
            name='Address',
            field=models.CharField(default='', max_length=50),
        ),
    ]
