# Generated by Django 2.0 on 2021-01-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0006_auto_20210126_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default='', upload_to='images/participant/'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='Image',
            field=models.ImageField(default='', upload_to='images/researcher/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='Image',
            field=models.ImageField(default='', upload_to='images/reviewer/'),
        ),
    ]
