# Generated by Django 2.0 on 2021-01-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0007_auto_20210126_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default="{% static 'img/avatar-01.jpg' %}", upload_to='images/participant/'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='Image',
            field=models.ImageField(default="{% static 'img/avatar-01.jpg' %}", upload_to='images/researcher/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='Image',
            field=models.ImageField(default="{% static 'img/avatar-01.jpg' %}", upload_to='images/reviewer/'),
        ),
    ]
