# Generated by Django 2.0 on 2021-01-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0010_auto_20210127_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default='abc.jpg', upload_to='images/participant/'),
        ),
    ]
