# Generated by Django 2.0 on 2021-01-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0011_auto_20210127_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default='static/img/avatar-01.jpg', upload_to='images/participant/'),
        ),
    ]
