# Generated by Django 2.0 on 2021-01-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0013_auto_20210127_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/participant/'),
        ),
    ]
