# Generated by Django 2.0 on 2021-01-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0014_auto_20210127_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default='default.jpg', max_length=255, upload_to='images/participant/'),
        ),
    ]
