# Generated by Django 2.0 on 2021-01-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0015_auto_20210127_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/researcher/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='Image',
            field=models.ImageField(default='default.jpg', upload_to='images/reviewer/'),
        ),
    ]
