# Generated by Django 2.0 on 2021-02-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0017_auto_20210127_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=100)),
                ('File', models.FileField(upload_to='files/')),
            ],
        ),
    ]
