# Generated by Django 2.0 on 2021-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0019_auto_20210203_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='File',
            field=models.FileField(default='', upload_to='files/'),
        ),
    ]
