# Generated by Django 2.0 on 2021-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0020_auto_20210203_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='File',
            field=models.FileField(default='Abc.pdf', upload_to='files/'),
        ),
    ]
