# Generated by Django 2.2 on 2021-02-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0023_conference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conference',
        ),
    ]
