# Generated by Django 2.0 on 2021-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0024_delete_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Conference_Type', models.CharField(choices=[('Off', 'Offline'), ('On', 'Online')], max_length=100)),
            ],
        ),
    ]
