# Generated by Django 2.0 on 2021-02-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0026_auto_20210210_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conference_Theme', models.CharField(choices=[('SM', 'Strategic Management'), ('AF', 'Accounting & Finance'), ('M', 'Marketing'), ('HRM', 'Human Resource Management'), ('EI', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100)),
                ('Conference_Mode', models.CharField(choices=[('Off', 'Offline'), ('On', 'Online')], max_length=100)),
                ('Date', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Place', models.CharField(blank=True, max_length=100)),
                ('Online_Link', models.CharField(blank=True, max_length=100)),
                ('Abstract_Submission_Date', models.TimeField()),
                ('Abstract_Acceptance_Date', models.TimeField()),
                ('FullPaper_Submission_Date', models.TimeField()),
                ('FullPaper_Acceptance_Date', models.TimeField()),
                ('Conference_Description', models.CharField(max_length=200)),
            ],
        ),
    ]
