# Generated by Django 2.0 on 2021-02-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0027_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='Conference_Description',
            field=models.TextField(),
        ),
    ]
