# Generated by Django 2.0 on 2021-02-11 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0028_auto_20210210_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_Theme', models.CharField(choices=[('SM', 'Strategic Management'), ('AF', 'Accounting & Finance'), ('M', 'Marketing'), ('HRM', 'Human Resource Management'), ('EI', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100)),
                ('Feedback_Description', models.TextField(max_length=200)),
                ('Feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.User')),
            ],
        ),
    ]
