# Generated by Django 2.0 on 2021-02-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0030_auto_20210211_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='Conference_Description',
            field=models.TextField(),
        ),
    ]
