# Generated by Django 2.0 on 2021-02-11 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0031_auto_20210211_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='Conference_Mode',
        ),
    ]
