# Generated by Django 2.0 on 2021-02-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0032_remove_conference_conference_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Conference_Mode',
            field=models.BooleanField(default=False, verbose_name='Online'),
        ),
    ]
