# Generated by Django 2.0 on 2021-02-11 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0033_conference_conference_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='Conference_Mode',
            new_name='Conference_Mode2',
        ),
        migrations.AddField(
            model_name='conference',
            name='Conference_Mode1',
            field=models.BooleanField(default=False, verbose_name='Offline'),
        ),
    ]
