# Generated by Django 2.0 on 2021-02-11 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0034_auto_20210211_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='Conference_Mode2',
        ),
        migrations.AlterField(
            model_name='conference',
            name='Conference_Mode1',
            field=models.BooleanField(verbose_name='Offline'),
        ),
    ]
