# Generated by Django 2.0 on 2021-02-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0035_auto_20210211_1324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Conference',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='Feedback_user',
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
