# Generated by Django 2.0 on 2021-02-11 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0036_auto_20210211_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conference_Theme', models.CharField(choices=[('SM', 'Strategic Management'), ('AF', 'Accounting & Finance'), ('M', 'Marketing'), ('HRM', 'Human Resource Management'), ('EI', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100)),
                ('Conference_Mode', models.CharField(choices=[('Off', 'Offline'), ('On', 'Online')], max_length=100)),
                ('Date', models.DateField()),
                ('Start_Time', models.TimeField()),
                ('End_Time', models.TimeField()),
                ('Place', models.CharField(blank=True, max_length=100)),
                ('Online_Link', models.CharField(blank=True, max_length=100)),
                ('Abstract_Submission_Date', models.DateField()),
                ('Abstract_Acceptance_Date', models.DateField()),
                ('FullPaper_Submission_Date', models.DateField()),
                ('FullPaper_Acceptance_Date', models.DateField()),
                ('Conference_Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_Theme', models.CharField(choices=[('SM', 'Strategic Management'), ('AF', 'Accounting & Finance'), ('M', 'Marketing'), ('HRM', 'Human Resource Management'), ('EI', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100)),
                ('Feedback_Description', models.TextField(max_length=200)),
                ('Feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.User')),
            ],
        ),
    ]
