# Generated by Django 2.2 on 2021-02-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0037_conference_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='Conference_Mode',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Conference_Theme',
            field=models.CharField(choices=[('Strategic Management', 'Strategic Management'), ('Accounting & Finance', 'Accounting & Finance'), ('Marketing', 'Marketing'), ('Human Resource Management', 'Human Resource Management'), ('Enterpreneueship and Innovations', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100),
        ),
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
