# Generated by Django 2.2 on 2021-02-12 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0038_auto_20210212_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback_Date', models.DateTimeField(auto_now_add=True)),
                ('Feedback_Theme', models.CharField(choices=[('Strategic Management', 'Strategic Management'), ('Accounting & Finance', 'Accounting & Finance'), ('Marketing', 'Marketing'), ('Human Resource Management', 'Human Resource Management'), ('Enterpreneueship and Innovations', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100)),
                ('Feedback_Description', models.TextField(max_length=200)),
                ('Feedback_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.User')),
            ],
        ),
    ]
