# Generated by Django 2.2 on 2021-02-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0040_user_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conference_Theme', models.CharField(choices=[('Strategic Management', 'Strategic Management'), ('Accounting & Finance', 'Accounting & Finance'), ('Marketing', 'Marketing'), ('Human Resource Management', 'Human Resource Management'), ('Enterpreneueship and Innovations', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100)),
                ('Institute', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=150)),
                ('Category', models.CharField(max_length=20)),
                ('Designation', models.CharField(max_length=50)),
                ('Payment_method', models.CharField(max_length=20)),
                ('Participant_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Participant')),
            ],
        ),
    ]
