# Generated by Django 2.2 on 2021-03-03 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0049_remove_researcher_registration_co_authors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Co_author',
        ),
    ]
