# Generated by Django 2.2 on 2021-03-03 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0051_co_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Co_author',
        ),
    ]
