# Generated by Django 2.2 on 2021-03-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0055_researcher_registration_co_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcher_registration',
            name='co_authors',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
