# Generated by Django 2.2 on 2021-03-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0056_auto_20210306_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcher_registration',
            name='Payment_method',
        ),
    ]
