# Generated by Django 2.2 on 2021-03-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0057_remove_researcher_registration_payment_method'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Researcher_registration',
        ),
    ]
