# Generated by Django 2.2 on 2021-03-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0059_researcher_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Researcher_registration',
        ),
    ]
