# Generated by Django 2.0 on 2021-03-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0061_researcher_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co_author',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='co_author',
            name='Category',
        ),
        migrations.DeleteModel(
            name='Co_author',
        ),
    ]
