# Generated by Django 2.0 on 2021-03-08 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0063_co_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='co_author',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='co_author',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='co_author',
            name='Registration_FK',
        ),
        migrations.RemoveField(
            model_name='researcher_registration',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='researcher_registration',
            name='Researcher_users',
        ),
        migrations.DeleteModel(
            name='Co_author',
        ),
        migrations.DeleteModel(
            name='Researcher_registration',
        ),
    ]
