# Generated by Django 2.0 on 2021-03-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0064_auto_20210308_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submission_Date', models.DateTimeField(auto_now_add=True)),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('File', models.FileField(default='Abc.pdf', upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Co_author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Mr.', max_length=10)),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Institute', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=150)),
                ('Designation', models.CharField(max_length=50)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Researcher')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.RegCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher_registration',
            fields=[
                ('Registraion_number', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Conference_Theme', models.CharField(choices=[('Strategic Management', 'Strategic Management'), ('Accounting & Finance', 'Accounting & Finance'), ('Marketing', 'Marketing'), ('Human Resource Management', 'Human Resource Management'), ('Enterpreneueship and Innovations', 'Enterpreneueship and Innovations'), ('IT', 'IT')], max_length=100)),
                ('Institute', models.CharField(max_length=50)),
                ('Address', models.TextField(max_length=150)),
                ('Designation', models.CharField(max_length=50)),
                ('Members', models.CharField(blank=True, max_length=10)),
                ('co_authors', models.CharField(blank=True, max_length=100)),
                ('Total_amount', models.IntegerField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.RegCategory')),
                ('Researcher_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Researcher')),
            ],
        ),
        migrations.AddField(
            model_name='co_author',
            name='Registration_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Researcher_registration'),
        ),
        migrations.AddField(
            model_name='abstract',
            name='Registration_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Researcher_registration'),
        ),
    ]
