# Generated by Django 2.0 on 2021-03-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0065_auto_20210308_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='Registration_FK',
        ),
        migrations.DeleteModel(
            name='Abstract',
        ),
    ]
