# Generated by Django 2.0 on 2021-03-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0067_abstract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='Registration_FK',
        ),
        migrations.DeleteModel(
            name='Abstract',
        ),
    ]
