# Generated by Django 2.0 on 2021-03-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0070_researcher_registration_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant_registration',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='participant_registration',
            name='Participant_users',
        ),
        migrations.DeleteModel(
            name='Participant_registration',
        ),
    ]
