# Generated by Django 2.0 on 2021-03-16 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0074_participant_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Reviewer'),
        ),
    ]
