# Generated by Django 2.0 on 2021-03-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0076_auto_20210318_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review_abstract',
            name='Abstract',
        ),
        migrations.RemoveField(
            model_name='review_abstract',
            name='Researcher',
        ),
        migrations.DeleteModel(
            name='Review_Abstract',
        ),
    ]
