# Generated by Django 2.0 on 2021-03-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0078_review_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_abstract',
            name='Reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='review_abstract',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
    ]
