# Generated by Django 2.2 on 2021-03-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0080_fullpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_Fullpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100)),
                ('Evaluation', models.CharField(blank=True, max_length=100)),
                ('Reviews', models.TextField(blank=True)),
                ('Reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Reviewer')),
                ('fullpaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Abstract')),
            ],
        ),
    ]
