# Generated by Django 2.2 on 2021-03-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0081_review_fullpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_fullpaper',
            name='fullpaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Fullpaper'),
        ),
    ]
