# Generated by Django 2.2 on 2021-04-09 03:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0082_auto_20210319_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Theme_name', models.CharField(max_length=100)),
                ('Sub_themes', django_mysql.models.ListTextField(models.CharField(max_length=100), size=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='review_abstract',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='review_fullpaper',
            name='Status',
        ),
        migrations.AddField(
            model_name='abstract',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abstract',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='fullpaper',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fullpaper',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='conference',
            name='Conference_Theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Theme'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default='default.png', max_length=255, upload_to='images/participant/'),
        ),
        migrations.AlterField(
            model_name='participant_registration',
            name='Conference_Theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Conference'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='images/researcher/'),
        ),
        migrations.AlterField(
            model_name='researcher_registration',
            name='Conference_Theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.Conference'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='Image',
            field=models.ImageField(default='default.png', upload_to='images/reviewer/'),
        ),
    ]
