# Generated by Django 3.1.7 on 2021-04-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0083_auto_20210409_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Include_Breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conference',
            name='Include_Lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conference',
            name='Include_Tea_Coffee',
            field=models.BooleanField(default=False),
        ),
    ]
