# Generated by Django 3.1.7 on 2021-04-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0084_auto_20210409_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Full_Paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cawa_app.fullpaper')),
            ],
        ),
    ]
