# Generated by Django 2.2 on 2021-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0088_auto_20210409_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='Image',
            field=models.ImageField(default='avtar.png', max_length=255, upload_to='images/participant/'),
        ),
        migrations.AlterField(
            model_name='researcher',
            name='Image',
            field=models.ImageField(default='avtar.png', upload_to='images/researcher/'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='Image',
            field=models.ImageField(default='avtar.png', upload_to='images/reviewer/'),
        ),
    ]
