# Generated by Django 3.1.7 on 2021-05-08 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0089_auto_20210414_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='End_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
