# Generated by Django 3.1.7 on 2021-05-09 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cawa_app', '0090_conference_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='Participant_registration_end_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conference',
            name='Participant_registration_start_Date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
